version: '3.8'

services:
  insco-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insco-app
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./config:/app/config
      - /tmp:/tmp
    tmpfs:
      - /tmp/.X11-unix
    environment:
      - ENVIRONMENT=production
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive
      # Configuración adicional para LibreOffice
      - HOME=/tmp
      - UNO_PATH=/usr/lib/libreoffice/program
      - URE_BOOTSTRAP=file:///usr/lib/libreoffice/program/fundamental.ini
      - PYTHONPATH=/usr/lib/libreoffice/program
    # Desactivamos el health check inicialmente hasta que confirmar que todo funciona
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    command: >
      bash -c "
        mkdir -p /tmp/.config/libreoffice && 
        chmod -R 777 /tmp/.config && 
        python -m uvicorn backend.main:app --host 0.0.0.0 --port 8088
      "

  # Nginx para servir el frontend y hacer de proxy para el backend
  nginx:
    image: nginx:alpine
    container_name: insco-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - insco-app 