version: '3.8'

services:
  insco-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insco-app
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - ENVIRONMENT=production
      - TZ=Europe/Madrid

  # Nginx para servir el frontend y hacer de proxy para el backend
  nginx:
    image: nginx:alpine
    container_name: insco-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - insco-app 