services:
  insco-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insco-app
    restart: always
    ports:
      - "8088:8088"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./config:/app/config
      - ./backend/config/auth_credentials.json:/app/config/auth_credentials.json
    environment:
      - ENVIRONMENT=production
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.insco-app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.insco-app.entrypoints=websecure"
      - "traefik.http.routers.insco-app.tls=true"
      - "traefik.http.services.insco-app.loadbalancer.server.port=8088"

volumes:
  mongodb_data: 